export const CREATE_PLANI_FAIL = "CREATE_PLANI_FAIL";
export const PLANI_INIT = "PLANI_INIT";
export const FETCH_PLANI_SUCCESS = "FETCH_PLANI_SUCCESS";
export const FETCH_PLANI_FAIL = "FETCH_PLANI_FAIL";
export const FETCH_PLANI_START = "FETCH_PLANI_START";
export const CLEAR_ERROR = "CLEAR_ERROR";
